"""Initiales Schema: user, track, track_session, lap

Revision ID: 89bdabad1b22
Revises: 
Create Date: 2026-09-15 13:26:44.316863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bdabad1b22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('length_m', sa.Integer(), nullable=False),
    sa.Column('reference_lap_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('track_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('car', sa.String(length=64), nullable=False),
    sa.Column('track_condition', sa.String(length=8), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_session_track_id'), ['track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_session_user_id'), ['user_id'], unique=False)

    op.create_table('lap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('sector1_ms', sa.Integer(), nullable=False),
    sa.Column('sector2_ms', sa.Integer(), nullable=False),
    sa.Column('sector3_ms', sa.Integer(), nullable=False),
    sa.Column('total_ms', sa.Integer(), nullable=False),
    sa.Column('lap_type', sa.String(length=8), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('invalid_reason', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['track_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'lap_number')
    )
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lap_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lap_total_ms'), ['total_ms'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lap_total_ms'))
        batch_op.drop_index(batch_op.f('ix_lap_session_id'))

    op.drop_table('lap')
    with op.batch_alter_table('track_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_track_session_track_id'))

    op.drop_table('track_session')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('track')
    # ### end Alembic commands ###
